### ISSUE TITLE
Store vacation get's overridden by other woocommerce_is_purchasable filter

### ISSUE THREAD

**Issue by ytterx** [mypreview/woo-store-vacation#2]
The priority of woocommerce_is_purchasable is set to -1, this means the function is always executed first, but if a rogue plugin or anything else is adding another filter on woocommerce_is_purchasable, the value get's overridden.

This means that for many cases, woocommerce still allows items to be bought, while I disabled it though this plugin...

An option to use a very high priority so it get's called at the very last filter would correct this.

You could argue that this is a bug in wordpress or another plugin, but there is no way to check the value of the "previous" filter outcome (as far as I know) which would help with the logic to make it an "AND" filter instead of "OR" like it currently behaves.

I also created a bug / feature request on woocommerce:"
https://github.com/woocommerce/woocommerce/issues/25558

**Comment by mahdiyazdani** [comment]
What is the name of the extension that you are using which hooks into the `woocommerce_is_purchasable` filter and alters it somehow?

**Comment by ytterx** [comment]
I think the plugin that breaks it is non-purchasable-woocommerce-products: https://wordpress.org/plugins/non-purchasable-woocommerce-products/

**Comment by mahdiyazdani** [comment]
Thanks for shedding some light on this matter. Please update to the latest available version for the fix.
