### ISSUE TITLE
PHP 81.9 

### ISSUE THREAD

**Issue by gooklani** [mypreview/woo-store-vacation#24]
The following error happens after updating the date.

```
woo-store-vacation.php:563
wp_kses_post( $data = NULL )
```

<img width="1432" alt="Screenshot 2022-12-20 at 8 19 24 PM" src="https://user-images.githubusercontent.com/25322810/208727563-8b9f6a00-f6fc-4736-bf5d-beb3553d61a1.png">

**Comment by mahdiyazdani** [comment]
Thank you @gooklani 🙌 
Closing this issue as I couldn’t replicate it in my testing environment. Please feel free to re-open by sharing additional debug information when you discover more.
